---
- hosts: filebeat
  sudo: yes
  gather_facts: no
  vars_files: 
    - ../defaults/main.yml
# tasks file for elk
  tasks:
    - name: Add Kafka user
      user:
        name: kafka
        group: sudo
        password: $6$kafkapass$wKf0u0RrBUDpAL1g/Tlp8HVbrA7OMwSW8uPdiqv9Hvz5kIqJo7XBKsChKYxvSiB2Go/IRanBx2nAxv8bi4OvU.

    - name: Add repo
      apt_repository:
        repo: 'ppa:webupd8team/java'
        state: present

    - name: Accept Java8 license
      shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections 

    - name: Setup Java8
      apt:
        name: oracle-java8-installer
        state: present
        update_cache: yes
        force: yes
    
    - name: Download Kafka tar
      get_url:
        url: "{{ kafka_download_url }}"
        dest: "{{ kafka_home }}/kafka.tgz"

    - name: Extract tar
      unarchive:
        src: "{{ kafka_home }}/kafka.tgz"
        dest: "{{ kafka_home }}"
        remote_src: yes
      
    - name: Update cache
      apt:
        update_cache: yes

    - name: Rename kafka directory
      command: "mv {{ kafka_home }}/kafka_2.12-2.1.0 {{ kafka_home }}/kafka"

    - name: Configure Kafka
      copy:
        src: "{{ item.files }}"
        dest: "{{ item.dests }}"
      with_items:
        - { files: '../files/server.properties', dests: '"{{ kafka_home }}"/kafka/config/server.properties'  }
        - { files: '../files/zookeeper.service', dests: '"{{ systemd_config_dir }}"/zookeeper.service' }
        - { files: '../files/kafka.service', dests: '"{{ systemd_config_dir }}"/kafka.service' }

    - name: Install systemd
      apt:
        name: systemd
        state: present

    - name: Start Kafka
      service:
        name: kafka
        state: started

